services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wanderer_dev
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  wanderer:
    environment:
      PORT: 4444
      DB_HOST: db
      WEB_APP_URL: "http://localhost:4444"
      ERL_AFLAGS: "-kernel shell_history enabled"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 4444:4444
    networks:
      - default
    volumes:
      - ..:/app:delegated
      - elixir-deps:/app/deps            # cache deps
      - elixir-build:/app/_build         # cache build artifacts
    command: sleep infinity
    user: "vscode"                  # run as non-root user
    depends_on:
      - db

volumes:
  elixir-deps:
  elixir-build:
  db: {}