import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :wanderer_app, WandererAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :wanderer_app, WandererApp.Repo,
  ssl: false,
  stacktrace: true,
  show_sensitive_data_on_connection_error: false,
  pool_size: 15,
  migration_timestamps: [type: :utc_datetime_usec],
  migration_lock: nil,
  queue_target: 5000,
  queue_interval: 1000,
  checkout_timeout: 15000

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: WandererApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger,
  level: :info

# Enable async security audit processing in production
config :wanderer_app, WandererApp.SecurityAudit, async: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
