import { ConnectionType, MassState, ShipSizeStatus } from '@/hooks/Mapper/types';

export enum SOLAR_SYSTEM_CLASS_IDS {
  ccp1 = -1,
  c1 = 1,
  c2 = 2,
  c3 = 3,
  c4 = 4,
  c5 = 5,
  c6 = 6,
  hs = 7,
  ls = 8,
  ns = 9,
  ccp2 = 10,
  ccp3 = 11,
  thera = 12,
  c13 = 13,
  sentinel = 14,
  barbican = 15,
  vidette = 16,
  conflux = 17,
  redoubt = 18,
  a1 = 19,
  a2 = 20,
  a3 = 21,
  a4 = 22,
  a5 = 23,
  ccp4 = 24,
  pochven = 25,
  zarzakh = 10100,
}

export enum SOLAR_SYSTEM_CLASS_GROUPS {
  ccp = 'ccp',
  c1 = 'c1',
  c2 = 'c2',
  c3 = 'c3',
  c4 = 'c4',
  c5 = 'c5',
  c6 = 'c6',
  hs = 'hs',
  ls = 'ls',
  ns = 'ns',
  thera = 'thera',
  c13 = 'c13',
  drifter = 'drifter',
  unknown = 'unknown',
  pochven = 'pochven',
  jovian = 'jovian',
}

export const SOLAR_SYSTEM_TO_CLASS_GROUPS_CLASSES = {
  c1: ['c1'],
  c2: ['c2'],
  c3: ['c3'],
  c4: ['c4'],
  c5: ['c5'],
  c6: ['c6'],
  hs: ['hs'],
  ls: ['ls'],
  ns: ['ns'],
  thera: ['thera'],
  c13: ['c13'],
  pochven: ['pochven'],
  drifter: ['sentinel', 'barbican', 'vidette', 'conflux', 'redoubt'],
  jove: ['jove'],
};

export const SOLAR_SYSTEM_CLASSES_TO_CLASS_GROUPS = {
  ccp1: SOLAR_SYSTEM_CLASS_GROUPS.ccp,
  c1: SOLAR_SYSTEM_CLASS_GROUPS.c1,
  c2: SOLAR_SYSTEM_CLASS_GROUPS.c2,
  c3: SOLAR_SYSTEM_CLASS_GROUPS.c3,
  c4: SOLAR_SYSTEM_CLASS_GROUPS.c4,
  c5: SOLAR_SYSTEM_CLASS_GROUPS.c5,
  c6: SOLAR_SYSTEM_CLASS_GROUPS.c6,
  hs: SOLAR_SYSTEM_CLASS_GROUPS.hs,
  ls: SOLAR_SYSTEM_CLASS_GROUPS.ls,
  ns: SOLAR_SYSTEM_CLASS_GROUPS.ns,
  ccp2: SOLAR_SYSTEM_CLASS_GROUPS.ccp,
  ccp3: SOLAR_SYSTEM_CLASS_GROUPS.ccp,
  thera: SOLAR_SYSTEM_CLASS_GROUPS.thera,
  c13: SOLAR_SYSTEM_CLASS_GROUPS.c13,
  sentinel: SOLAR_SYSTEM_CLASS_GROUPS.drifter,
  barbican: SOLAR_SYSTEM_CLASS_GROUPS.drifter,
  vidette: SOLAR_SYSTEM_CLASS_GROUPS.drifter,
  conflux: SOLAR_SYSTEM_CLASS_GROUPS.drifter,
  redoubt: SOLAR_SYSTEM_CLASS_GROUPS.drifter,
  a1: SOLAR_SYSTEM_CLASS_GROUPS.unknown,
  a2: SOLAR_SYSTEM_CLASS_GROUPS.unknown,
  a3: SOLAR_SYSTEM_CLASS_GROUPS.unknown,
  a4: SOLAR_SYSTEM_CLASS_GROUPS.unknown,
  a5: SOLAR_SYSTEM_CLASS_GROUPS.unknown,
  ccp4: SOLAR_SYSTEM_CLASS_GROUPS.ccp,
  pochven: SOLAR_SYSTEM_CLASS_GROUPS.pochven,
};

type WormholesAdditionalInfoType = {
  id: string;
  shortName: string;
  wormholeClassID: number;
  title: string;
  shortTitle: string;
  effectPower?: number;
};

// TODO - maybe we need store it on backend. But not sure
export const WORMHOLES_ADDITIONAL_INFO_RAW: WormholesAdditionalInfoType[] = [
  {
    id: 'ccp1',
    shortName: 'CCP',
    wormholeClassID: -1,
    title: 'CCP System',
    shortTitle: 'CCP',
  },
  {
    id: 'c1',
    shortName: 'C1',
    wormholeClassID: 1,
    effectPower: 1,
    title: 'Class 1',
    shortTitle: 'C1',
  },
  {
    id: 'c2',
    shortName: 'C2',
    wormholeClassID: 2,
    effectPower: 2,
    title: 'Class 2',
    shortTitle: 'C2',
  },
  {
    id: 'c3',
    shortName: 'C3',
    wormholeClassID: 3,
    effectPower: 3,
    title: 'Class 3',
    shortTitle: 'C3',
  },
  {
    id: 'c4',
    shortName: 'C4',
    wormholeClassID: 4,
    effectPower: 4,
    title: 'Class 4',
    shortTitle: 'C4',
  },
  {
    id: 'c5',
    shortName: 'C5',
    wormholeClassID: 5,
    effectPower: 5,
    title: 'Class 5',
    shortTitle: 'C5',
  },
  {
    id: 'c6',
    shortName: 'C6',
    wormholeClassID: 6,
    effectPower: 6,
    title: 'Class 6',
    shortTitle: 'C6',
  },
  {
    id: 'hs',
    shortName: 'H',
    wormholeClassID: 7,
    title: 'High-sec',
    shortTitle: 'High-sec',
  },
  {
    id: 'ls',
    shortName: 'L',
    wormholeClassID: 8,
    title: 'Low-sec',
    shortTitle: 'Low-sec',
  },
  {
    id: 'ns',
    shortName: 'N',
    wormholeClassID: 9,
    title: 'Null-sec',
    shortTitle: 'Null-sec',
  },
  {
    id: 'ccp2',
    shortName: 'CCP',
    wormholeClassID: 10,
    title: 'CCP System',
    shortTitle: 'CCP',
  },
  {
    id: 'ccp3',
    shortName: 'CCP',
    wormholeClassID: 11,
    title: 'CCP System',
    shortTitle: 'CCP',
  },
  {
    id: 'thera',
    shortName: 'T',
    wormholeClassID: 12,
    title: 'Class 12 (Thera)',
    shortTitle: 'Thera',
  },
  {
    id: 'c13',
    shortName: 'C13',
    wormholeClassID: 13,
    effectPower: 6,
    title: 'Class 13 (Shattered Frigate)',
    shortTitle: 'C13',
  },
  {
    id: 'sentinel',
    shortName: 'D',
    wormholeClassID: 14,
    effectPower: 2,
    title: 'Class 14 (Sentinel Drifter)',
    shortTitle: 'Sentinel MZ',
  },
  {
    id: 'barbican',
    shortName: 'D',
    wormholeClassID: 15,
    effectPower: 2,
    title: 'Class 15 (Barbican Drifter)',
    shortTitle: 'Liberated Barbican',
  },
  {
    id: 'vidette',
    shortName: 'D',
    wormholeClassID: 16,
    effectPower: 2,
    title: 'Class 16 (Vidette Drifter)',
    shortTitle: 'Sanctified Vidette',
  },
  {
    id: 'conflux',
    shortName: 'D',
    wormholeClassID: 17,
    effectPower: 2,
    title: 'Class 17 (Conflux Drifter)',
    shortTitle: 'Conflux Eyrie',
  },
  {
    id: 'redoubt',
    shortName: 'D',
    wormholeClassID: 18,
    effectPower: 2,
    title: 'Class 18 (Redoubt Drifter)',
    shortTitle: 'Azdaja Redoubt',
  },
  {
    id: 'a1',
    shortName: 'A1',
    wormholeClassID: 19,
    title: '(Abyssal class 1)',
    shortTitle: 'A1',
  },
  {
    id: 'a2',
    shortName: 'A2',
    wormholeClassID: 20,
    title: '(Abyssal class 2)',
    shortTitle: 'A2',
  },
  {
    id: 'a3',
    shortName: 'A3',
    wormholeClassID: 21,
    title: '(Abyssal class 3)',
    shortTitle: 'A3',
  },
  {
    id: 'a4',
    shortName: 'A4',
    wormholeClassID: 22,
    title: '(Abyssal class 4)',
    shortTitle: 'A4',
  },
  {
    id: 'a5',
    shortName: 'A5',
    wormholeClassID: 23,
    title: '(Abyssal class 5)',
    shortTitle: 'A5',
  },
  {
    id: 'ccp4',
    shortName: 'CCP',
    wormholeClassID: 24,
    title: 'CCP System (Penalty)',
    shortTitle: 'CCP',
  },
  {
    id: 'pochven',
    shortName: 'P',
    wormholeClassID: 25,
    title: 'Triglavian space (Pochven)',
    shortTitle: 'Pochven',
  },
  {
    id: 'zarzakh',
    shortName: 'N',
    wormholeClassID: 10100,
    title: 'Pirate space',
    shortTitle: 'Zarzakh',
  },
  {
    id: 'k162',
    shortName: 'K162',
    wormholeClassID: 10101,
    title: 'Reverse',
    shortTitle: 'K162',
  },
];

export const WORMHOLES_ADDITIONAL_INFO: Record<string, WormholesAdditionalInfoType> =
  WORMHOLES_ADDITIONAL_INFO_RAW.reduce((acc, x) => ({ ...acc, [x.id]: x }), {});

export const WORMHOLES_ADDITIONAL_INFO_BY_CLASS_ID: Record<string, WormholesAdditionalInfoType> =
  WORMHOLES_ADDITIONAL_INFO_RAW.reduce((acc, x) => ({ ...acc, [x.wormholeClassID]: x }), {});

export const WORMHOLES_ADDITIONAL_INFO_BY_SHORT_NAME: Record<string, WormholesAdditionalInfoType> =
  WORMHOLES_ADDITIONAL_INFO_RAW.reduce((acc, x) => ({ ...acc, [x.shortName]: x }), {});

// export const SOLAR_SYSTEM_CLASS_NAMES = {
//   ccp1 =  ,
//   c1 = ,
//   c2 = ,
//   c3 = ,
//   c4 = ,
//   c5 = ,
//   c6 = ,
//   hs = ,
//   ls = ,
//   ns = ,
//   ccp2 = ,
//   ccp3 = ,
//   thera = ,
//   c13 = ,
//   sentinel = ,
//   baribican = ,
//   vidette = ,
//   conflux = ,
//   redoubt = ,
//   a1 = ,
//   a2 = ,
//   a3 = ,
//   a4 = ,
//   a5 = ,
//   ccp4 = ,
//   pochven = ,
//   zarzakh = ,
// }

export const REGION_SHORT_NAME: Record<string, string> = {
  Aridia: 'Aridia',
  'Black Rise': 'Black Rise',
  'The Bleak Lands': 'Bl. Lands',
  'The Citadel': 'The Citadel',
  Derelik: 'Derelik',
  Devoid: 'Devoid',
  Domain: 'Domain',
  Essence: 'Essence',
  Everyshore: 'Everyshore',
  'The Forge': 'The Forge',
  Genesis: 'Genesis',
  Heimatar: 'Heimatar',
  Kador: 'Kador',
  Khanid: 'Khanid',
  'Kor-Azor': 'Kor-Azor',
  Lonetrek: 'Lonetrek',
  Metropolis: 'Metropolis',
  'Molden Heath': 'Molden H.',
  Placid: 'Placid',
  'Sinq Laison': 'S. Laison',
  Solitude: 'Solitude',
  'Tash-Murkon': 'Tash-M.',
  'Verge Vendor': 'Verge V.',
  Branch: 'Branch',
  Cache: 'Cache',
  Catch: 'Catch',
  'Cloud Ring': 'Cloud Ring',
  'Cobalt Edge': 'Cobalt E.',
  Curse: 'Curse',
  Deklein: 'Deklein',
  Delve: 'Delve',
  Detorid: 'Detorid',
  Esoteria: 'Esoteria',
  'Etherium Reach': 'Etherium R.',
  Fade: 'Fade',
  Feythabolis: 'Feythabolis',
  Fountain: 'Fountain',
  Geminate: 'Geminate',
  'Great Wildlands': 'G. Wild.',
  Immensea: 'Immensea',
  Impass: 'Impass',
  Insmother: 'Insmother',
  'The Kalevala Expanse': 'Kalevala E.',
  Malpais: 'Malpais',
  Oasa: 'Oasa',
  Omist: 'Omist',
  'Outer Passage': 'O. Passage',
  'Outer Ring': 'Outer Ring',
  'Paragon Soul': 'Paragon S.',
  'Period Basis': 'Period B.',
  'Perrigen Falls': 'Perrigen F.',
  Pochven: 'Pochven',
  Providence: 'Providence',
  'Pure Blind': 'Pure Blind',
  Querious: 'Querious',
  'Scalding Pass': 'Scalding P.',
  'The Spire': 'The Spire',
  Stain: 'Stain',
  Syndicate: 'Syndicate',
  Tenal: 'Tenal',
  Tenerifis: 'Tenerifis',
  Tribute: 'Tribute',
  'Vale of the Silent': 'V. Silent',
  Venal: 'Venal',
  'Wicked Creek': 'Wicked C.',
};

export const SECURITY_FOREGROUND_CLASSES: Record<string, string> = {
  '1.0': 'eve-security-color-10',
  '0.9': 'eve-security-color-09',
  '0.8': 'eve-security-color-08',
  '0.7': 'eve-security-color-07',
  '0.6': 'eve-security-color-06',
  '0.5': 'eve-security-color-05',
  '0.4': 'eve-security-color-04',
  '0.3': 'eve-security-color-03',
  '0.2': 'eve-security-color-02',
  '0.1': 'eve-security-color-01',
  '0.0': 'eve-security-color-00',
  '-0.0': 'eve-security-color-00',
  '-0.1': 'eve-security-color-m-01',
  '-0.2': 'eve-security-color-m-02',
  '-0.3': 'eve-security-color-m-03',
  '-0.4': 'eve-security-color-m-04',
  '-0.5': 'eve-security-color-m-05',
  '-0.6': 'eve-security-color-m-06',
  '-0.7': 'eve-security-color-m-07',
  '-0.8': 'eve-security-color-m-08',
  '-0.9': 'eve-security-color-m-09',
  '-1.0': 'eve-security-color-m-10',
};

export const SECURITY_BACKGROUND_CLASSES: Record<string, string> = {
  '1.0': 'eve-security-background-10',
  '0.9': 'eve-security-background-09',
  '0.8': 'eve-security-background-08',
  '0.7': 'eve-security-background-07',
  '0.6': 'eve-security-background-06',
  '0.5': 'eve-security-background-05',
  '0.4': 'eve-security-background-04',
  '0.3': 'eve-security-background-03',
  '0.2': 'eve-security-background-02',
  '0.1': 'eve-security-background-01',
  '0.0': 'eve-security-background-00',
  '-0.0': 'eve-security-background-00',
  '-0.1': 'eve-security-background-m-01',
  '-0.2': 'eve-security-background-m-02',
  '-0.3': 'eve-security-background-m-03',
  '-0.4': 'eve-security-background-m-04',
  '-0.5': 'eve-security-background-m-05',
  '-0.6': 'eve-security-background-m-06',
  '-0.7': 'eve-security-background-m-07',
  '-0.8': 'eve-security-background-m-08',
  '-0.9': 'eve-security-background-m-09',
  '-1.0': 'eve-security-background-m-10',
};

export const SYSTEM_CLASS_BACKGROUND_CLASSES: Record<string, string> = {
  '-1': '',
  '1': 'eve-kind-background-wh',
  '2': 'eve-kind-background-wh',
  '3': 'eve-kind-background-wh',
  '4': 'eve-kind-background-wh',
  '5': 'eve-kind-background-wh',
  '6': 'eve-kind-background-wh',
  '7': 'eve-kind-background-high',
  '8': 'eve-kind-background-low',
  '9': 'eve-kind-background-null',
  '10': '',
  '11': '',
  '12': 'eve-kind-background-thera',
  '13': 'eve-kind-background-wh',
  '14': 'eve-kind-background-wh',
  '15': 'eve-kind-background-wh',
  '16': 'eve-kind-background-wh',
  '17': 'eve-kind-background-wh',
  '18': 'eve-kind-background-wh',
  '19': 'eve-kind-background-abyss',
  '20': 'eve-kind-background-abyss',
  '21': 'eve-kind-background-abyss',
  '22': 'eve-kind-background-abyss',
  '23': 'eve-kind-background-abyss',
  '24': 'eve-kind-background-penalty',
  '25': 'eve-kind-background-pochven',
  '10100': 'eve-kind-background-zarzakh',
};

export const WORMHOLE_CLASS_BACKGROUND_CLASSES: Record<string, string> = {
  '1': 'eve-wh-type-background-c1',
  '2': 'eve-wh-type-background-c2',
  '3': 'eve-wh-type-background-c3',
  '4': 'eve-wh-type-background-c4',
  '5': 'eve-wh-type-background-c5',
  '6': 'eve-wh-type-background-c6',
  '7': 'eve-wh-type-background-high',
  '8': 'eve-wh-type-background-low',
  '9': 'eve-wh-type-background-null',
  '12': 'eve-wh-type-background-thera',
  '13': 'eve-wh-type-background-c13',
  '14': 'eve-wh-type-background-drifter',
  '15': 'eve-wh-type-background-drifter',
  '16': 'eve-wh-type-background-drifter',
  '17': 'eve-wh-type-background-drifter',
  '18': 'eve-wh-type-background-drifter',
  '25': 'eve-wh-type-background-null',
  '10100': 'eve-wh-type-background-null',
};

export const WORMHOLE_CLASS_STYLES: Record<string, string> = {
  '-1': '',
  '1': 'eve-wh-type-color-c1',
  '2': 'eve-wh-type-color-c2',
  '3': 'eve-wh-type-color-c3',
  '4': 'eve-wh-type-color-c4',
  '5': 'eve-wh-type-color-c5',
  '6': 'eve-wh-type-color-c6',
  '7': 'eve-wh-type-color-high',
  '8': 'eve-wh-type-color-low',
  '9': 'eve-wh-type-color-null',
  '10': '',
  '11': '',
  '12': 'eve-wh-type-color-thera',
  '13': 'eve-wh-type-color-c13',
  '14': 'eve-wh-type-color-drifter',
  '15': 'eve-wh-type-color-drifter',
  '16': 'eve-wh-type-color-drifter',
  '17': 'eve-wh-type-color-drifter',
  '18': 'eve-wh-type-color-drifter',
  '19': 'eve-kind-color-abyss',
  '20': 'eve-kind-color-abyss',
  '21': 'eve-kind-color-abyss',
  '22': 'eve-kind-color-abyss',
  '23': 'eve-kind-color-abyss',
  '24': 'eve-kind-color-penalty',
  '25': 'eve-wh-type-color-null',
  '10100': 'eve-wh-type-color-thera',
};

export const SYSTEM_CLASS_STYLES: Record<string, string> = {
  '-1': '',
  '1': 'eve-kind-color-wh',
  '2': 'eve-kind-color-wh',
  '3': 'eve-kind-color-wh',
  '4': 'eve-kind-color-wh',
  '5': 'eve-kind-color-wh',
  '6': 'eve-kind-color-wh',
  '7': 'eve-kind-color-high',
  '8': 'eve-kind-color-low',
  '9': 'eve-kind-color-null',
  '10': '',
  '11': '',
  '12': 'eve-kind-color-thera',
  '13': 'eve-kind-color-wh',
  '14': 'eve-kind-color-wh',
  '15': 'eve-kind-color-wh',
  '16': 'eve-kind-color-wh',
  '17': 'eve-kind-color-wh',
  '18': 'eve-kind-color-wh',
  '19': 'eve-kind-color-abyss',
  '20': 'eve-kind-color-abyss',
  '21': 'eve-kind-color-abyss',
  '22': 'eve-kind-color-abyss',
  '23': 'eve-kind-color-abyss',
  '24': 'eve-kind-color-penalty',
  '25': 'eve-kind-color-pochven',
  '10100': 'eve-kind-color-zarzakh',
};

export enum EFFECT_NAME {
  pulsar = 'Pulsar',
  magnetar = 'Magnetar',
  wolfRayetStar = 'Wolf-Rayet Star',
  blackHole = 'Black Hole',
  cataclysmicVariable = 'Cataclysmic Variable',
  redGiant = 'Red Giant',
  dazhLiminalityLocus = 'Dazh Liminality Locus',
  imperialStellarObservatory = 'Imperial Stellar Observatory',
  stateStellarObservatory = 'State Stellar Observatory',
  republicStellarObservatory = 'Republic Stellar Observatory',
  federalStellarObservatory = 'Federal Stellar Observatory',
}

export const EFFECT_FOREGROUND_STYLES: Record<string, string> = {
  Pulsar: 'text-eve-wh-effect-color-pulsar',
  Magnetar: 'text-eve-wh-effect-color-magnetar',
  'Wolf-Rayet Star': 'text-eve-wh-effect-color-wolfRayet',
  'Black Hole': 'text-eve-wh-effect-color-blackHole',
  'Cataclysmic Variable': 'text-eve-wh-effect-color-cataclysmicVariable',
  'Red Giant': 'text-eve-wh-effect-color-redGiant',

  'Dazh Liminality Locus': 'text-eve-wh-effect-color-dazhLiminalityLocus',
  'Imperial Stellar Observatory': 'text-eve-wh-effect-color-imperialStellarObservatory',
  'State Stellar Observatory': 'text-eve-wh-effect-color-stateStellarObservatory',
  'Republic Stellar Observatory': 'text-eve-wh-effect-color-republicStellarObservatory',
  'Federal Stellar Observatory': 'text-eve-wh-effect-color-federalStellarObservatory',
};

export const EFFECT_BACKGROUND_STYLES: Record<string, string> = {
  Pulsar: 'eve-wh-effect-color-pulsar',
  Magnetar: 'eve-wh-effect-color-magnetar',
  'Wolf-Rayet Star': 'eve-wh-effect-color-wolfRayet',
  'Black Hole': 'eve-wh-effect-color-blackHole',
  'Cataclysmic Variable': 'eve-wh-effect-color-cataclysmicVariable',
  'Red Giant': 'eve-wh-effect-color-redGiant',
  'Dazh Liminality Locus': 'eve-wh-effect-color-dazhLiminalityLocus',
  'Imperial Stellar Observatory': 'eve-wh-effect-color-imperialStellarObservatory',
  'State Stellar Observatory': 'eve-wh-effect-color-stateStellarObservatory',
  'Republic Stellar Observatory': 'eve-wh-effect-color-republicStellarObservatory',
  'Federal Stellar Observatory': 'eve-wh-effect-color-federalStellarObservatory',
};

export const MARKER_BOOKMARK_BG_STYLES: Record<string, string> = {
  custom: 'wd-marker-bookmark-color-custom',
  shattered: 'wd-marker-bookmark-color-shattered',
  a0: 'wd-marker-bookmark-color-a0',
  activityNormal: 'wd-marker-bookmark-color-normal',
  activityWarn: 'wd-marker-bookmark-color-warn',
  activityDanger: 'wd-marker-bookmark-color-danger',

  la: 'wd-marker-bookmark-color-average',
  lb: 'wd-marker-bookmark-color-ytirium',
  lc: 'wd-marker-bookmark-color-ytirium',
  l1: 'wd-marker-bookmark-color-l1',
  l2: 'wd-marker-bookmark-color-l2',
  l3: 'wd-marker-bookmark-color-l3',
};

export enum LABELS {
  clear = 'clear',
  la = 'a',
  lb = 'b',
  lc = 'c',
  l1 = '1',
  l2 = '2',
  l3 = '3',
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const LABELS_INFO: Record<string, any> = {
  [LABELS.clear]: { id: 'clear', name: 'Clear', shortName: '', icon: '' },
  [LABELS.la]: { id: 'la', name: 'Label A', shortName: 'A', icon: '' },
  [LABELS.lb]: { id: 'lb', name: 'Label B', shortName: 'B', icon: '' },
  [LABELS.lc]: { id: 'lc', name: 'Label C', shortName: 'C', icon: '' },
  [LABELS.l1]: { id: 'l1', name: 'Label 1', shortName: '1', icon: '' },
  [LABELS.l2]: { id: 'l2', name: 'Label 2', shortName: '2', icon: '' },
  [LABELS.l3]: { id: 'l3', name: 'Label 3', shortName: '3', icon: '' },
};

export enum STATUSES {
  unknown,
  home,
  friendly,
  lookingFor,
  warning,
  target,
  dangerous,
}

export const STATUS_NAMES = {
  [STATUSES.unknown]: 'Clear',
  [STATUSES.home]: 'Home',
  [STATUSES.friendly]: 'Friendly',
  [STATUSES.lookingFor]: 'Looking for',
  [STATUSES.warning]: 'Warning',
  [STATUSES.target]: 'Target',
  [STATUSES.dangerous]: 'Dangerous',
};

export const STATUSES_ORDER = [
  STATUSES.unknown,
  STATUSES.home,
  STATUSES.friendly,
  STATUSES.lookingFor,
  STATUSES.warning,
  STATUSES.target,
  STATUSES.dangerous,
];

export const LABELS_ORDER = [LABELS.clear, LABELS.la, LABELS.lb, LABELS.lc, LABELS.l1, LABELS.l2, LABELS.l3];

export const STATUS_COLOR_CLASSES: Record<number, string> = {
  [STATUSES.unknown]: 'eve-system-status-color-clear',
  [STATUSES.home]: 'eve-system-status-color-home',
  [STATUSES.friendly]: 'eve-system-status-color-friendly',
  [STATUSES.lookingFor]: 'eve-system-status-color-lookingFor',
  [STATUSES.warning]: 'eve-system-status-color-warning',
  [STATUSES.target]: 'eve-system-status-color-target',
  [STATUSES.dangerous]: 'eve-system-status-color-dangerous',
};

export const STATUS_CLASSES: Record<number, string> = {
  [STATUSES.unknown]: 'eve-system-status-clear',
  [STATUSES.home]: 'eve-system-status-home',
  [STATUSES.friendly]: 'eve-system-status-friendly',
  [STATUSES.lookingFor]: 'eve-system-status-lookingFor',
  [STATUSES.warning]: 'eve-system-status-warning',
  [STATUSES.target]: 'eve-system-status-target',
  [STATUSES.dangerous]: 'eve-system-status-dangerous',
};

export const TYPE_NAMES_ORDER = [ConnectionType.wormhole, ConnectionType.gate, ConnectionType.bridge];

export const TYPE_NAMES = {
  [ConnectionType.wormhole]: 'Wormhole',
  [ConnectionType.gate]: 'Gate',
  [ConnectionType.bridge]: 'Jumpgate',
};

export const MASS_STATE_NAMES_ORDER = [MassState.verge, MassState.half, MassState.normal];

export const MASS_STATE_NAMES = {
  [MassState.normal]: 'Normal',
  [MassState.half]: 'Half',
  [MassState.verge]: 'Verge of collapse',
};

export const SHIP_SIZES_NAMES_ORDER = [
  ShipSizeStatus.small,
  ShipSizeStatus.medium,
  ShipSizeStatus.large,
  ShipSizeStatus.freight,
  ShipSizeStatus.capital,
];

export const SHIP_SIZES_NAMES = {
  [ShipSizeStatus.small]: 'Frigate',
  [ShipSizeStatus.medium]: 'Medium',
  [ShipSizeStatus.large]: 'Normal',
  [ShipSizeStatus.freight]: 'Huge',
  [ShipSizeStatus.capital]: 'Capital',
};
export const SHIP_SIZES_SIZE = {
  [ShipSizeStatus.small]: '5K',
  [ShipSizeStatus.medium]: '62K',
  [ShipSizeStatus.large]: '375K',
  [ShipSizeStatus.freight]: '1M',
  [ShipSizeStatus.capital]: '2M',
};

export const SHIP_MASSES_SIZE: Record<number, ShipSizeStatus> = {
  5_000_000: ShipSizeStatus.small,
  62_000_000: ShipSizeStatus.medium,
  300_000_000: ShipSizeStatus.large,
  375_000_000: ShipSizeStatus.large,
  1_000_000_000: ShipSizeStatus.freight,
  1_350_000_000: ShipSizeStatus.capital,
  1_800_000_000: ShipSizeStatus.capital,
  2_000_000_000: ShipSizeStatus.capital,
};

export const SHIP_SIZES_DESCRIPTION = {
  [ShipSizeStatus.small]: 'Frigate wormhole - up to Destroyer | 5K t.',
  [ShipSizeStatus.medium]: 'Cruise wormhole - up to Battlecruiser | 62K t.',
  [ShipSizeStatus.large]: 'Large wormhole - up to Battleship | 375K t.',
  [ShipSizeStatus.freight]: 'Huge wormhole - up to Freighter | 1M t.',
  [ShipSizeStatus.capital]: 'Capital wormhole - up to Capital | 2M t.',
};

export const SHIP_SIZES_NAMES_SHORT = {
  [ShipSizeStatus.small]: 'S',
  [ShipSizeStatus.medium]: 'M',
  [ShipSizeStatus.large]: 'L',
  [ShipSizeStatus.freight]: 'H',
  [ShipSizeStatus.capital]: 'XL',
};
