defmodule WandererApp.Repo.Migrations.AddMaps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:maps_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :description, :text
      add :personal_note, :text
      add :hubs, {:array, :text}, default: []

      add :owner_id,
          references(:character_v1,
            column: :id,
            name: "maps_v1_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:maps_v1, "maps_v1_owner_id_fkey")

    drop table(:maps_v1)
  end
end
