defmodule WandererApp.Repo.Migrations.UpdateChainParams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_v1) do
      modify :locked, :boolean, default: false
    end
  end

  def down do
    alter table(:map_system_v1) do
      modify :locked, :boolean, default: true
    end
  end
end
