defmodule WandererApp.Repo.Migrations.AddMapScopeRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "UPDATE maps_v1 SET scope = 'wormholes' WHERE scope IS NULL"

    alter table(:maps_v1) do
      modify :scope, :text, null: false
    end
  end

  def down do
    alter table(:maps_v1) do
      modify :scope, :text, null: true
    end
  end
end
