defmodule WandererApp.Repo.Migrations.MapSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :slug, :text, null: false
    end

    create unique_index(:maps_v1, [:slug], name: "maps_v1_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:maps_v1, [:slug], name: "maps_v1_unique_slug_index")

    alter table(:maps_v1) do
      remove :slug
    end
  end
end
