defmodule WandererApp.Repo.Migrations.AddMapConnectionLocked do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_chain_v1) do
      add :locked, :boolean
    end
  end

  def down do
    alter table(:map_chain_v1) do
      remove :locked
    end
  end
end
