defmodule WandererApp.Repo.Migrations.RemoveUserWandereBalanceEncription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_v1) do
      remove :wanderer_balance
    end
  end

  def down do
    alter table(:user_v1) do
      add :wanderer_balance, :float, default: 0.0
    end
  end
end
