defmodule WandererApp.Repo.Migrations.CharacterLocaction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :solar_system_id, :bigint
      add :structure_id, :bigint
    end
  end

  def down do
    alter table(:character_v1) do
      remove :structure_id
      remove :solar_system_id
    end
  end
end
