defmodule WandererApp.Repo.Migrations.AclRolesUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:access_list_members_v1) do
      modify :role, :text, null: true, default: nil
    end
  end

  def down do
    alter table(:access_list_members_v1) do
      modify :role, :text, null: false, default: "member"
    end
  end
end
