defmodule WandererApp.Repo.Migrations.UpdateMapSubscriptionAutoRenew do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_subscriptions_v1) do
      add :auto_renew?, :boolean, null: false
    end
  end

  def down do
    alter table(:map_subscriptions_v1) do
      remove :auto_renew?
    end
  end
end
