defmodule WandererApp.Repo.Migrations.CharacterWalletBalance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :wallet_ballance, :text
    end
  end

  def down do
    alter table(:character_v1) do
      remove :wallet_ballance
    end
  end
end
