defmodule WandererApp.Repo.Migrations.AddMapChainPassagesShipName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_chain_passages_v1) do
      add :ship_name, :text
    end
  end

  def down do
    alter table(:map_chain_passages_v1) do
      remove :ship_name
    end
  end
end
