defmodule WandererApp.Repo.Migrations.AddCorpWalletEncoded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:corp_wallet_transactions_v1) do
      add :encrypted_amount_encoded, :binary, null: false
      add :encrypted_balance_encoded, :binary, null: false
      add :encrypted_first_party_id_encoded, :binary, null: false
      add :encrypted_second_party_id_encoded, :binary, null: false
      add :encrypted_reason_encoded, :binary
    end
  end

  def down do
    alter table(:corp_wallet_transactions_v1) do
      remove :encrypted_reason_encoded
      remove :encrypted_second_party_id_encoded
      remove :encrypted_first_party_id_encoded
      remove :encrypted_balance_encoded
      remove :encrypted_amount_encoded
    end
  end
end
