defmodule WandererApp.Repo.Migrations.ShipSize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_chain_v1) do
      modify :ship_size_type, :bigint, default: 2
    end
  end

  def down do
    alter table(:map_chain_v1) do
      modify :ship_size_type, :bigint, default: 1
    end
  end
end
