defmodule WandererApp.Repo.Migrations.CharacterDeletedFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :deleted, :boolean, default: false
    end
  end

  def down do
    alter table(:character_v1) do
      remove :deleted
    end
  end
end
