defmodule WandererApp.Repo.Migrations.AddCharacterCorporationAllianceInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :corporation_id, :bigint
      add :corporation_name, :text
      add :corporation_ticker, :text
      add :alliance_id, :bigint
      add :alliance_name, :text
      add :alliance_ticker, :text
    end
  end

  def down do
    alter table(:character_v1) do
      remove :alliance_ticker
      remove :alliance_name
      remove :alliance_id
      remove :corporation_ticker
      remove :corporation_name
      remove :corporation_id
    end
  end
end
