defmodule WandererApp.Repo.Migrations.AddMapScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :scope, :text, default: "wormholes"
    end

    create_if_not_exists unique_index(:map_character_settings_v1, [:map_id, :character_id],
                           name: "map_character_settings_v1_uniq_map_character_index"
                         )
  end

  def down do
    drop_if_exists unique_index(:map_character_settings_v1, [:map_id, :character_id],
                     name: "map_character_settings_v1_uniq_map_character_index"
                   )

    alter table(:maps_v1) do
      remove :scope
    end
  end
end
