defmodule WandererApp.Repo.Migrations.RemoveCorpWalletUnencoded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:corp_wallet_transactions_v1) do
      remove :reason
      remove :second_party_id
      remove :first_party_id
      remove :balance
      remove :amount
    end
  end

  def down do
    alter table(:corp_wallet_transactions_v1) do
      add :amount, :float, null: false
      add :balance, :float, null: false
      add :first_party_id, :bigint, null: false
      add :second_party_id, :bigint, null: false
      add :reason, :text
    end
  end
end
