defmodule WandererApp.Repo.Migrations.AddMapOptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :options, :text
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :options
    end
  end
end
