defmodule WandererApp.Repo.Migrations.AddCharacterShipName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :ship_name, :text
    end

    alter table(:access_list_members_v1) do
      modify :role, :text, null: true
    end
  end

  def down do
    alter table(:access_list_members_v1) do
      modify :role, :text, null: false
    end

    alter table(:character_v1) do
      remove :ship_name
    end
  end
end
