defmodule WandererApp.Repo.Migrations.AddMapSystemSignatures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_system_signatures_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :eve_id, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :kind, :text
      add :group, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :system_id,
          references(:map_system_v1,
            column: :id,
            name: "map_system_signatures_v1_system_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:map_system_signatures_v1, [:system_id, :eve_id],
             name: "map_system_signatures_v1_uniq_system_eve_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_system_signatures_v1, [:system_id, :eve_id],
                     name: "map_system_signatures_v1_uniq_system_eve_id_index"
                   )

    drop constraint(:map_system_signatures_v1, "map_system_signatures_v1_system_id_fkey")

    drop table(:map_system_signatures_v1)
  end
end
