defmodule WandererApp.Repo.Migrations.AddMapSolarSystems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_solar_system_v2, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :region_id, :bigint
      add :constellation_id, :bigint
      add :solar_system_id, :bigint
      add :solar_system_name, :text
      add :solar_system_name_lc, :text
      add :constellation_name, :text
      add :region_name, :text
      add :system_class, :bigint
      add :security, :text
      add :type_description, :text
      add :class_title, :text
      add :is_shattered, :boolean
      add :effect_name, :text
      add :effect_power, :bigint
      add :statics, {:array, :text}, default: []
      add :wandering, {:array, :text}, default: []
      add :triglavian_invasion_status, :text
      add :sun_type_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:map_solar_system_v2, [:solar_system_id],
             name: "map_solar_system_v2_solar_system_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_solar_system_v2, [:solar_system_id],
                     name: "map_solar_system_v2_solar_system_id_index"
                   )

    drop table(:map_solar_system_v2)
  end
end
