defmodule WandererApp.Repo.Migrations.AddUserTransaction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_transaction_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :journal_ref_id, :bigint, null: false
      add :corporation_id, :bigint, null: false
      add :amount, :bigint, null: false
      add :date, :utc_datetime
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:user_v1,
            column: :id,
            name: "user_transaction_v1_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:user_transaction_v1, "user_transaction_v1_user_id_fkey")

    drop table(:user_transaction_v1)
  end
end
