defmodule WandererApp.Repo.Migrations.AddMapOnlyTrackedCharactersFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :only_tracked_characters, :boolean, default: false
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :only_tracked_characters
    end
  end
end
