defmodule WandererApp.Repo.Migrations.ShipTypesGroupName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ship_type_infos_v1) do
      modify :volume, :text
      add :group_name, :text
    end
  end

  def down do
    alter table(:ship_type_infos_v1) do
      remove :group_name
      modify :volume, :bigint
    end
  end
end
