defmodule WandererApp.Repo.Migrations.AddSignatureLinkedSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_signatures_v1) do
      add :linked_system_id, :bigint
    end
  end

  def down do
    alter table(:map_system_signatures_v1) do
      remove :linked_system_id
    end
  end
end
