defmodule WandererApp.Repo.Migrations.RemoveCorpWalletEncoded2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:corp_wallet_transactions_v1) do
      remove :second_party_id_encoded
      remove :first_party_id_encoded
    end
  end

  def down do
    alter table(:corp_wallet_transactions_v1) do
      add :first_party_id_encoded, :bigint, null: false
      add :second_party_id_encoded, :bigint, null: false
    end
  end
end
