defmodule WandererApp.Repo.Migrations.AddMapSolarSystemJumps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_solar_system_jumps_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_solar_system_id, :bigint
      add :to_solar_system_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:map_solar_system_jumps_v1, [:from_solar_system_id, :to_solar_system_id],
             name: "map_solar_system_jumps_v1_solar_system_from_to_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :map_solar_system_jumps_v1,
                     [:from_solar_system_id, :to_solar_system_id],
                     name: "map_solar_system_jumps_v1_solar_system_from_to_index"
                   )

    drop table(:map_solar_system_jumps_v1)
  end
end
