defmodule WandererApp.Repo.Migrations.MapAcls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_access_lists_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_access_lists_v1_map_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :access_list_id,
          references(:access_lists_v1,
            column: :id,
            name: "map_access_lists_v1_access_list_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:map_access_lists_v1, "map_access_lists_v1_map_id_fkey")

    drop constraint(:map_access_lists_v1, "map_access_lists_v1_access_list_id_fkey")

    drop table(:map_access_lists_v1)
  end
end
