defmodule WandererApp.Repo.Migrations.AddCharacterUniqEveId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:character_v1, [:eve_id], name: "character_v1_unique_eve_id_index")
  end

  def down do
    drop_if_exists unique_index(:character_v1, [:eve_id],
                     name: "character_v1_unique_eve_id_index"
                   )
  end
end
