defmodule WandererApp.Repo.Migrations.AddCorpWalletIdentityCheck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:corp_wallet_transactions_v1, [:eve_transaction_id],
             name: "corp_wallet_transactions_v1_eve_transaction_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:corp_wallet_transactions_v1, [:eve_transaction_id],
                     name: "corp_wallet_transactions_v1_eve_transaction_id_index"
                   )
  end
end
