defmodule WandererApp.Repo.Migrations.AddSystemIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:map_system_v1, [:map_id, :solar_system_id],
             name: "map_system_v1_map_solar_system_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_system_v1, [:map_id, :solar_system_id],
                     name: "map_system_v1_map_solar_system_id_index"
                   )
  end
end
