defmodule WandererApp.Repo.Migrations.UpdateMapSubscription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_subscriptions_v1) do
      add :characters_limit, :bigint, default: 100
      add :hubs_limit, :bigint, default: 10
    end
  end

  def down do
    alter table(:map_subscriptions_v1) do
      remove :hubs_limit
      remove :characters_limit
    end
  end
end
