defmodule WandererApp.Repo.Migrations.AddCharacterTrackingPool do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :tracking_pool, :text
    end
  end

  def down do
    alter table(:character_v1) do
      remove :tracking_pool
    end
  end
end
