defmodule WandererApp.Repo.Migrations.AddCharacterShipItemId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_v1) do
      add :ship_item_id, :bigint
    end
  end

  def down do
    alter table(:character_v1) do
      remove :ship_item_id
    end
  end
end
