defmodule WandererApp.Repo.Migrations.UpdateMapPingsV1ForApi do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_pings_v1) do
      modify :type, :text, null: false, default: "ping"
      add :expires_at, :utc_datetime
      add :acknowledged, :boolean, null: false, default: false
    end
  end

  def down do
    # First, clean up the type column to convert text values to numeric before casting
    execute """
    UPDATE map_pings_v1
    SET type = '0'
    WHERE type !~ '^[0-9]+$'
    """

    alter table(:map_pings_v1) do
      remove :acknowledged
      remove :expires_at
      modify :type, :bigint, null: true, default: 0
    end
  end
end
