defmodule WandererApp.Repo.Migrations.AddAclApiKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:access_lists_v1) do
      add :api_key, :text
    end
  end

  def down do
    alter table(:access_lists_v1) do
      remove :api_key
    end
  end
end
