defmodule WandererApp.Repo.Migrations.AddLicenseLmId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_licenses_v1) do
      add :lm_id, :text, null: false
    end
  end

  def down do
    alter table(:map_licenses_v1) do
      remove :lm_id
    end
  end
end
