defmodule WandererApp.Repo.Migrations.AddSystemOwner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_v1) do
      add :owner_id, :text
      add :owner_type, :text
    end
  end

  def down do
    alter table(:map_system_v1) do
      remove :owner_type
      remove :owner_id
    end
  end
end
