defmodule WandererApp.Repo.Migrations.AddMapSseEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :sse_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :sse_enabled
    end
  end
end
