defmodule WandererApp.Repo.Migrations.MapStateConnectionsStartTime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_state_v1) do
      add :connections_start_time, :binary
    end
  end

  def down do
    alter table(:map_state_v1) do
      remove :connections_start_time
    end
  end
end
