defmodule WandererApp.Repo.Migrations.AddMapCharacterTrackingInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_character_settings_v1) do
      add :encrypted_ship, :binary
      add :encrypted_ship_name, :binary
      add :encrypted_ship_item_id, :binary
      add :encrypted_solar_system_id, :binary
      add :encrypted_structure_id, :binary
      add :encrypted_station_id, :binary
    end
  end

  def down do
    alter table(:map_character_settings_v1) do
      remove :encrypted_station_id
      remove :encrypted_structure_id
      remove :encrypted_solar_system_id
      remove :encrypted_ship_item_id
      remove :encrypted_ship_name
      remove :encrypted_ship
    end
  end
end
