defmodule WandererApp.Repo.Migrations.AddSigUpdateForcedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_signatures_v1) do
      add :update_forced_at, :utc_datetime
    end
  end

  def down do
    alter table(:map_system_signatures_v1) do
      remove :update_forced_at
    end
  end
end
