defmodule WandererApp.Repo.Migrations.AddUniqueConstraintPublicApiKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Create unique index that allows multiple NULL values
    # (compatible with PostgreSQL 14 and earlier)
    create unique_index(:maps_v1, [:public_api_key],
             name: "maps_v1_unique_public_api_key_index",
             where: "public_api_key IS NOT NULL"
           )
  end

  def down do
    drop_if_exists unique_index(:maps_v1, [:public_api_key],
                     name: "maps_v1_unique_public_api_key_index"
                   )
  end
end
