defmodule WandererApp.Repo.Migrations.AddDeletedSignature do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_signatures_v1) do
      remove :updated
      add :deleted, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:map_system_signatures_v1) do
      remove :deleted
      add :updated, :bigint
    end
  end
end
