defmodule WandererApp.Repo.Migrations.AddMapPerformanceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:map_system_v1, [:map_id],
             name: "map_system_v1_map_id_visible_index",
             where: "visible = true"
           )

    create index(:map_chain_v1, [:map_id], name: "map_chain_v1_map_id_index")
  end

  def down do
    drop_if_exists index(:map_chain_v1, [:map_id], name: "map_chain_v1_map_id_index")

    drop_if_exists index(:map_system_v1, [:map_id], name: "map_system_v1_map_id_visible_index")
  end
end
