defmodule WandererApp.Repo.Migrations.AddFleetReadinessReadyCharacters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_user_settings_v1) do
      add :ready_characters, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:map_user_settings_v1) do
      remove :ready_characters
    end
  end
end
