defmodule WandererApp.Repo.Migrations.UpdatesForApiv1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_pings_v1) do
      modify :type, :text, null: false, default: "ping"
      add :expires_at, :utc_datetime
      add :acknowledged, :boolean, null: false, default: false
    end

    alter table(:map_invites_v1) do
      add :code, :text
      add :email, :text
      add :expires_at, :utc_datetime
      add :accepted_at, :utc_datetime
      add :revoked_at, :utc_datetime
      add :max_uses, :bigint, null: false, default: 1
      add :use_count, :bigint, null: false, default: 0

      add :inviter_id,
          references(:user_v1,
            column: :id,
            name: "map_invites_v1_inviter_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:map_invites_v1, "map_invites_v1_inviter_id_fkey")

    alter table(:map_invites_v1) do
      remove :inviter_id
      remove :use_count
      remove :max_uses
      remove :revoked_at
      remove :accepted_at
      remove :expires_at
      remove :email
      remove :code
    end

    alter table(:map_pings_v1) do
      remove :acknowledged
      remove :expires_at
      modify :type, :bigint, null: true, default: 0
    end
  end
end
