defmodule WandererApp.Repo.Migrations.AddMapUserSettingsMainFollowingIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_user_settings_v1) do
      add :main_character_eve_id, :text
      add :following_character_eve_id, :text
    end
  end

  def down do
    alter table(:map_user_settings_v1) do
      remove :following_character_eve_id
      remove :main_character_eve_id
    end
  end
end
