defmodule WandererApp.Repo.Migrations.AddSdeVersionTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sde_versions_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sde_version, :text, null: false
      add :source, :text, null: false
      add :release_date, :utc_datetime
      add :applied_at, :utc_datetime, null: false
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sde_versions_v1, [:applied_at])

    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: fragment("'{wormholes}'")
    end
  end

  def down do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: nil
    end

    drop_if_exists index(:sde_versions_v1, [:applied_at])

    drop table(:sde_versions_v1)
  end
end
