defmodule WandererApp.Repo.Migrations.AddSystemComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_system_comments_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :system_id,
          references(:map_system_v1,
            column: :id,
            name: "map_system_comments_v1_system_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :character_id,
          references(:character_v1,
            column: :id,
            name: "map_system_comments_v1_character_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:map_system_comments_v1, "map_system_comments_v1_system_id_fkey")

    drop constraint(:map_system_comments_v1, "map_system_comments_v1_character_id_fkey")

    drop table(:map_system_comments_v1)
  end
end
