defmodule WandererApp.Repo.Migrations.AddMapScopesDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: nil
    end
  end

  def down do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: []
    end
  end
end
