defmodule WandererApp.Repo.Migrations.SystemLinkedSigEveId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_v1) do
      add :linked_sig_eve_id, :text
    end
  end

  def down do
    alter table(:map_system_v1) do
      remove :linked_sig_eve_id
    end
  end
end
