defmodule WandererApp.Repo.Migrations.AddMapScopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :scopes, {:array, :text}, default: fragment("'{wormholes}'")
    end

    create_if_not_exists unique_index(:maps_v1, [:public_api_key],
                           name: "maps_v1_unique_public_api_key_index"
                         )

    drop_if_exists index(:map_system_v1, [:map_id], name: "map_system_v1_map_id_visible_index")
  end

  def down do
    create_if_not_exists index(:map_system_v1, [:map_id],
                           name: "map_system_v1_map_id_visible_index",
                           where: "visible = true"
                         )

    drop_if_exists unique_index(:maps_v1, [:public_api_key],
                     name: "maps_v1_unique_public_api_key_index"
                   )

    alter table(:maps_v1) do
      remove :scopes
    end
  end
end
