defmodule WandererApp.Repo.Migrations.AddLicenseIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:map_licenses_v1, [:map_id], name: "map_licenses_v1_uniq_map_id_index")
  end

  def down do
    drop_if_exists unique_index(:map_licenses_v1, [:map_id],
                     name: "map_licenses_v1_uniq_map_id_index"
                   )
  end
end
