defmodule WandererApp.Repo.Migrations.AddMapPings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_pings_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :bigint, default: 0
      add :message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_pings_v1_map_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :system_id,
          references(:map_system_v1,
            column: :id,
            name: "map_pings_v1_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :character_id,
          references(:character_v1,
            column: :id,
            name: "map_pings_v1_character_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:map_pings_v1, "map_pings_v1_map_id_fkey")

    drop constraint(:map_pings_v1, "map_pings_v1_system_id_fkey")

    drop constraint(:map_pings_v1, "map_pings_v1_character_id_fkey")

    drop table(:map_pings_v1)
  end
end
