defmodule WandererApp.Repo.Migrations.AddCharacterDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: '{wormholes}'
    end

    alter table(:character_v1) do
      add :description, :text
    end
  end

  def down do
    alter table(:character_v1) do
      remove :description
    end

    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: nil
    end
  end
end
