defmodule WandererApp.Repo.Migrations.AddMassToMapChainPassages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: '{wormholes}'
    end

    alter table(:map_chain_passages_v1) do
      add :mass, :bigint
    end
  end

  def down do
    alter table(:map_chain_passages_v1) do
      remove :mass
    end

    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: nil
    end
  end
end
