defmodule WandererApp.Repo.Migrations.AddMapDiscordNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_discord_notifications_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :enabled?, :boolean, null: false, default: true
      add :wh_only, :boolean, null: false, default: true
      add :excluded_systems, {:array, :bigint}, null: false, default: []
      add :last_delivery_at, :utc_datetime
      add :last_error, :text
      add :last_error_at, :utc_datetime
      add :consecutive_failures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_discord_notifications_v1_map_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_webhook_url, :binary, null: false
    end

    create unique_index(:map_discord_notifications_v1, [:map_id],
             name: "map_discord_notifications_v1_unique_map_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_discord_notifications_v1, [:map_id],
                     name: "map_discord_notifications_v1_unique_map_id_index"
                   )

    drop constraint(:map_discord_notifications_v1, "map_discord_notifications_v1_map_id_fkey")

    drop table(:map_discord_notifications_v1)
  end
end
