defmodule WandererApp.Repo.Migrations.AddRetentionCleanupIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:map_system_signatures_v1, [:updated_at],
             name: "map_system_signatures_v1_updated_at_index",
             concurrently: true
           )

    create index(:map_chain_passages_v1, [:updated_at],
             name: "map_chain_passages_v1_updated_at_index",
             concurrently: true
           )

    create index(
             :map_chain_passages_v1,
             [:map_id, :solar_system_source_id, :solar_system_target_id, :inserted_at],
             name: "map_chain_passages_v1_connection_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(
                     :map_chain_passages_v1,
                     [:map_id, :solar_system_source_id, :solar_system_target_id, :inserted_at],
                     name: "map_chain_passages_v1_connection_index"
                   )

    drop_if_exists index(:map_chain_passages_v1, [:updated_at],
                     name: "map_chain_passages_v1_updated_at_index"
                   )

    drop_if_exists index(:map_system_signatures_v1, [:updated_at],
                     name: "map_system_signatures_v1_updated_at_index"
                   )
  end
end
