defmodule WandererAppWeb.OpenApiV1Spec do
  @moduledoc """
  OpenAPI spec specifically for v1 JSON:API endpoints generated by AshJsonApi.

  This module delegates to WandererAppWeb.OpenApi for the actual specification.
  The schemas and paths are auto-generated by AshJsonApi from Ash resources.
  """

  @behaviour OpenApiSpex.OpenApi

  @impl OpenApiSpex.OpenApi
  def spec do
    # Delegate to the main OpenApi module which contains the actual spec
    WandererAppWeb.OpenApi.spec()
  end
end
