defmodule WandererAppWeb.OpenApiV1Spec do
  @moduledoc """
  OpenAPI spec specifically for v1 JSON:API endpoints generated by AshJsonApi.
  """

  @behaviour OpenApiSpex.OpenApi

  @impl OpenApiSpex.OpenApi
  def spec do
    # This is called by the modify_open_api option in the router
    # We delegate to WandererAppWeb.OpenApi module which generates
    # the spec from AshJsonApi with custom endpoints merged in
    WandererAppWeb.OpenApi.spec()
  end
end
