#!/bin/bash

echo "🚀 Wanderer API Hybrid Test Setup"
echo "================================="
echo ""
echo "This script will help you set up the hybrid API tests."
echo ""

# Check if .env exists
if [ -f "test/api/.env" ]; then
    echo "✅ Found existing .env file"
    echo "   Current settings:"
    grep -E "^(API_TOKEN|MAP_SLUG|ACL_)" test/api/.env | sed 's/=.*/=***/' | sed 's/^/   /'
    echo ""
    read -p "Do you want to update the settings? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing settings."
        exit 0
    fi
else
    echo "📝 Creating new .env file..."
    cp test/api/.env.example test/api/.env
fi

echo ""
echo "To set up the hybrid tests, you need:"
echo ""
echo "1. A Wanderer map with API access enabled"
echo "   - Log into Wanderer"
echo "   - Go to your map settings"
echo "   - Enable 'Public API'"
echo "   - Copy the API token"
echo ""
echo "2. (Optional) An ACL with API access"
echo "   - Go to ACL settings"
echo "   - Enable API access"
echo "   - Copy the API token"
echo ""

# Prompt for values
read -p "Enter your map's API token: " API_TOKEN
read -p "Enter your map's slug (from URL): " MAP_SLUG
read -p "Enter ACL API token (optional, press Enter to skip): " ACL_API_TOKEN
read -p "Enter ACL ID (optional, press Enter to skip): " ACL_ID

# Update .env file
cat > test/api/.env << EOF
# API Test Environment Variables
# Generated by setup_hybrid_tests.sh on $(date)

# Bearer token from an existing map's API settings
API_TOKEN=$API_TOKEN

# Map slug (the URL-friendly name of your map)
MAP_SLUG=$MAP_SLUG

# ACL API token (if testing ACL endpoints)
ACL_API_TOKEN=$ACL_API_TOKEN

# ACL ID for testing
ACL_ID=$ACL_ID

# Base URL for the API (optional, defaults to http://localhost:4000)
API_BASE_URL=http://localhost:4000

# Character ID for testing (optional)
TEST_CHARACTER_ID=95000001

# System IDs for testing (optional, defaults to Jita and Perimeter)
TEST_SYSTEM_ID_1=30000142
TEST_SYSTEM_ID_2=30000144
EOF

echo ""
echo "✅ Configuration saved to test/api/.env"
echo ""
echo "You can now run the hybrid tests with:"
echo "  mix test test/api/controllers/hybrid_api_test.exs"
echo ""
echo "Or run all API tests with:"
echo "  mix test test/api"