defmodule WandererAppWeb.OpenApiV1SpecTest do
  use ExUnit.Case, async: true

  alias WandererAppWeb.OpenApi

  @moduledoc """
  Tests for OpenAPI v1 specification to ensure:
  1. Token-only authentication is properly documented
  2. Bearer auth is required globally
  3. Documentation explains the token-only approach

  Note: Schemas and paths are auto-generated by AshJsonApi from Ash resources.
  To verify map_id handling in actions, check the Ash resource tests.
  This test focuses on the OpenAPI documentation and structure.
  """

  describe "OpenAPI spec structure" do
    test "spec returns valid OpenAPI structure" do
      spec = OpenApi.spec()

      assert %OpenApiSpex.OpenApi{} = spec
      assert spec.info.title == "WandererApp v1 JSON:API"
      assert spec.info.version == "1.0.0"
    end

    test "has bearer authentication security scheme" do
      spec = OpenApi.spec()

      assert spec.components.securitySchemes["bearerAuth"]
      assert spec.components.securitySchemes["bearerAuth"]["type"] == "http"
      assert spec.components.securitySchemes["bearerAuth"]["scheme"] == "bearer"
      assert spec.components.securitySchemes["bearerAuth"]["description"]
    end

    test "requires bearer auth globally" do
      spec = OpenApi.spec()

      assert [%{"bearerAuth" => []}] = spec.security
    end

    test "has servers configured" do
      spec = OpenApi.spec()

      assert is_list(spec.servers)
      assert length(spec.servers) > 0
    end
  end

  describe "authentication documentation" do
    test "documents token-only authentication" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "token-only authentication"
      assert description =~ "do **NOT** need to provide `map_id`"
      assert description =~ "determined from your API token"
    end

    test "explains where map_id should NOT be provided" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "Request body attributes"
      assert description =~ "Query parameters"
      assert description =~ "URL path"
    end

    test "explains how to get API token" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "Getting Your API Token"
      assert description =~ "Map Settings"
      assert description =~ "API Access"
    end

    test "includes security best practices" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "Security"
      assert description =~ "Never share your API tokens"
      assert description =~ "full access to its associated map"
    end

    test "mentions one token per map" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "Each map has its own unique API token"
    end
  end

  describe "API features documentation" do
    test "documents JSON:API features" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "Filtering"
      assert description =~ "Sorting"
      assert description =~ "Pagination"
      assert description =~ "Relationships"
    end

    test "explains filter syntax" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "filter[attribute]=value"
    end

    test "explains sort syntax" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "sort=attribute"
      assert description =~ "sort=-attribute"
    end

    test "explains pagination syntax" do
      spec = OpenApi.spec()
      description = spec.info.description

      assert description =~ "page[limit]"
      assert description =~ "page[offset]"
    end
  end

  describe "paths and schemas" do
    test "has paths generated from Ash resources" do
      spec = OpenApi.spec()

      assert is_map(spec.paths)
      assert map_size(spec.paths) > 0
    end

    test "has schemas generated from Ash resources" do
      spec = OpenApi.spec()

      assert is_map(spec.components.schemas)
      assert map_size(spec.components.schemas) > 0
    end

    test "has tags for organizing endpoints" do
      spec = OpenApi.spec()

      assert is_list(spec.tags)
    end

    test "includes custom systems_and_connections endpoint" do
      spec = OpenApi.spec()

      # This is a custom endpoint added in merge_custom_paths
      path_key =
        Enum.find(Map.keys(spec.paths), fn path ->
          String.contains?(path, "systems_and_connections")
        end)

      assert path_key, "Should have systems_and_connections custom endpoint"
    end
  end

  describe "responses" do
    test "has standard error responses" do
      spec = OpenApi.spec()

      assert is_map(spec.components.responses)
    end
  end

  describe "security scheme details" do
    test "bearer auth description mentions Map API key" do
      spec = OpenApi.spec()

      description = spec.components.securitySchemes["bearerAuth"]["description"]
      assert description =~ "Map API key"
    end
  end
end
