name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  MIX_ENV: test

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '26.0'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-quality-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-quality-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile (warnings as errors)
        env:
          SECRET_KEY_BASE: "test-secret-key-base-for-ci-only"
          GUARDIAN_SECRET_KEY: "test-guardian-secret-key-for-ci-only"
        run: mix compile --warnings-as-errors

      - name: Check code formatting
        run: mix format --check-formatted

      - name: Run Credo (high priority issues only)
        run: mix credo --strict --min-priority high --format oneline

      - name: Run unused dependency check
        run: mix deps.unlock --check-unused
        continue-on-error: true

      - name: Check for security vulnerabilities
        run: mix sobelow --config --format json --out sobelow-report.json || true
        continue-on-error: true

      - name: Generate code quality report
        if: always()
        run: |
          echo "## Code Quality Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Credo Issues" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          mix credo --format oneline 2>&1 || true >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY